language: python
python:
  - "3.8"
cache: pip
install:
  - pip install requests
script:
  - python run_tests_travis.py

notifications:
email:
    recipients:
    - tyler.tucker@colorado.edu
    - argovistesting@gmail.com
    on_success: never # default: change
    on_failure: always # default: always